routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logout', 'Auth\LoginController@logout', function () {
    return abort(404);
});

Route::resource('companies', 'CompanyController');
Route::resource('employees', 'EmployeeController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('set_locale/{locale}', function ($locale) {
    App::setLocale($locale);
    return redirect('/companies/create');
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Company extends Model
{
    protected $fillable = [
        'name', 'email', 'logo',
    ];

    protected $guarded = [ 'id' ];

    public function employees()
    {
        return $this->hasMany(Employee::class);
    }

    public function delete()
    {
        $delete = DB::transaction(function () {
            $this->employees()->delete();
            $deleteParent = parent::delete();
            return $deleteParent;
        });

        return $delete;
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreCompany;
use App\Models\Company;
use Illuminate\Support\Facades\Redirect;
use Image;
use Illuminate\Http\Request;
use App\Domain\Services\CompanyService;
use Illuminate\Support\Facades\Storage;

class CompanyController extends Controller
{
    private $companyService;

    public function __construct(CompanyService $companyService)
    {
        $this->companyService = $companyService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = $this->companyService->all();
        return view('companies.index')->with('companies', $companies);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCompany $request)
    {
        $request->validated();
        $requestData = $this->validateAndSaveImage($request);
        $requestData = ($requestData) ? $requestData : $request->all();
        $this->companyService->create($requestData);
        return Redirect::to('companies')
            ->with('message', trans('view.messages.success', ['action' => trans('view.messages.actions.store')]));
    }

    /**
     * Display the specified resource.
     *
     * @param Company $company
     * @return \Illuminate\Http\RedirectResponse
     */
    public function show(Company $company)
    {
        if (!$company) {
            return Redirect::to('companies')->with('error', trans('views.messages.error_not_found'));
        }

        return view('companies.show')->with('company', $company);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Company $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        if (!$company) {
            return Redirect::to('companies')
                ->with('error', trans('views.messages.error_not_found'));
        }

        return view('companies.edit')->with('company', $company);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param StoreCompany $request
     * @param Company $company
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(StoreCompany $request, Company $company)
    {
        if (!$company) {
            return Redirect::to('companies')->with('error', trans('views.messages.error_not_found'));
        }
        $request->validated();
        $requestData = $this->validateAndSaveImage($request);
        $requestData = ($requestData) ? $requestData : $request->all();
        $this->companyService->update($requestData, $company->id);
        return Redirect::to('companies')
            ->with('message', trans('view.messages.success', ['action' => trans('view.messages.actions.update')]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Company $company
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Company $company)
    {
        if (!$company) {
            return Redirect::to('companies')
                ->with('error', trans('views.messages.error_not_found'));
        }

        $company = $this->companyService->delete($company->id);
        return Redirect::to('companies')
            ->with('message', trans('view.messages.success', ['action' => trans('view.messages.actions.delete')]));
    }

    private function validateAndSaveImage($request)
    {
        if ($request->hasFile('logo')) {
            $image = $request->file('logo');
            $fileName = time() . '.' . $image->getClientOriginalExtension();

            $img = Image::make($image->getRealPath());
            $img->resize(120, 120, function ($constraint) {
                $constraint->aspectRatio();
            });

            $img->stream();

            Storage::disk('local')->put('/public/' . $fileName, $img, 'public');
            $requestData = $request->all();
            $requestData['logo'] = $fileName;
            return $requestData;
        }

        return false;
    }
}

resources/views/companies/create.blade.php
@extends("theme.$theme.layout")

@section('content')
    <div class="row">
        <div class="col-lg-12">
            @include('includes.form-error')
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3>@lang('view.companies.form.title_form')</h3>
                </div>
                <div class="box-body">
                    <form role="form" action="{{route('companies.store')}}" method="post" enctype="multipart/form-data" autocomplete="off">
                        @csrf
                        <div class="box-body">
                            @include('companies.form')
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            @include('includes.btn-form-create')
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/companies/edit.blade.php
@extends("theme.$theme.layout")

@section('content')
    <div class="row">
        <div class="col-lg-12">
            @include('includes.form-error')
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3>@lang('view.companies.form.title_form')</h3>
                </div>
                <div class="box-body">
                    <form role="form" action="{{route('companies.update', $company)}}" method="post" enctype="multipart/form-data" autocomplete="off">
                        @csrf
                        @method('PUT')
                        <div class="box-body">
                            @include('companies.form')
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            @include('includes.btn-form-edit')
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/companies/form.blade.php
<div class="form-group">
    <label for="exampleInputName" class="required">@lang('view.companies.form.name')</label>
    <input type="text" class="form-control" id="exampleInputName" name="name" placeholder="Enter name" value="{{old('name', $company->name ?? '')}}" required>
</div>
<div class="form-group">
    <label for="exampleInputEmail1">@lang('view.companies.form.email')</label>
    <input type="email" class="form-control" id="exampleInputEmail1" name="email" placeholder="Enter email" value="{{old('email', $company->email ?? '')}}">
</div>
<div class="form-group">
    <label for="exampleInputFile">@lang('view.companies.form.logo')</label>
    <input type="file" name="logo" id="exampleInputFile">

    <p class="help-block">with 100 x 100.</p>
</div>

resources/views/companies/index.blade.php
@extends("theme.$theme.layout")

@section('content')
    <div class="row">
        <div class="col-lg-12">
            @include('includes.message')
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3>List Companies</h3> <a href="{{url('companies/create')}}" class="btn btn-success">Create new
                        company</a>
                </div>
                <div class="box-body">
                    @if(isset($companies) && count($companies) > 0)
                        <table class="table table-bordered">
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th style="width: 150px">Logo</th>
                                <th>Actions</th>
                            </tr>
                            @foreach($companies as $key => $company)
                                <tr>
                                    <td>{{$key + 1}}</td>
                                    <td>{{$company->name}}</td>
                                    <td>
                                        {{$company->email}}
                                    </td>
                                    <td>
                                        @if($company->logo)
                                            <img src="{{ asset('storage/' . $company->logo) }}">
                                        @else
                                            Sin logo
                                        @endif
                                    </td>
                                    <td>
                                        <form action="{{ route('companies.destroy',$company->id) }}" method="POST">
                                            <a href="{{url('companies/' . $company->id , 'edit')}}"
                                               class="btn btn-primary">Edit</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                        {{ $companies->links() }}
                    @else
                        Empty data
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection