routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logout', 'Auth\LoginController@logout', function () {
    return abort(404);
});

Route::resource('companies', 'CompanyController');
Route::resource('employees', 'EmployeeController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('set_locale/{locale}', function ($locale) {
    App::setLocale($locale);
    return redirect('/companies/create');
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = [
        'name', 'last_name', 'company_id', 'email', 'phone'
    ];

    protected $guarded = [ 'id' ];

    public function company()
    {
        /** @var TYPE_NAME $this */
        return $this->belongsTo(Company::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Domain\Services\CompanyService;
use App\Domain\Services\EmployeeService;
use App\Http\Requests\StoreEmployee;
use App\Models\Employee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class EmployeeController extends Controller
{
    private $employeeService;
    private $companyService;

    public function __construct(
        EmployeeService $employeeService,
        CompanyService $companyService
    )
    {
        $this->employeeService = $employeeService;
        $this->companyService = $companyService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = $this->employeeService->all();
        return view('employees.index')->with('employees', $employees);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = $this->companyService->all();
        return view('employees.create')->with('companies', $companies);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEmployee $request)
    {
        $request->validated();
        $this->employeeService->create($request->all());
        return Redirect::to('employees')
            ->with('message', trans('view.messages.success', ['action' => trans('view.messages.actions.store')]));
    }

    /**
     * Display the specified resource.
     *
     * @param Employee $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        if (!$employee) {
            return Redirect::to('employees')->with('error', trans('views.messages.error_not_found'));
        }

        return view('employees.show')->with('employee', $employee);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Employee $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        if (!$employee) {
            return Redirect::to('employees')
                ->with('error', trans('views.messages.error_not_found'));
        }
        $companies = $this->companyService->all();
        return view('employees.edit')->with('employee', $employee)->with('companies', $companies);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreEmployee $request, Employee $employee)
    {
        if (!$employee) {
            return Redirect::to('employees')->with('error', trans('views.messages.error_not_found'));
        }
        $request->validated();
        $this->employeeService->update($request->all(), $employee->id);
        return Redirect::to('employees')
            ->with('message', trans('view.messages.success', ['action' => trans('view.messages.actions.update')]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Employee $employee
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Employee $employee)
    {
        if (!$employee) {
            return Redirect::to('employees')
                ->with('error', trans('views.messages.error_not_found'));
        }

        $employee = $this->employeeService->delete($employee->id);
        return Redirect::to('employees')
            ->with('message', trans('view.messages.success', ['action' => trans('view.messages.actions.delete')]));
    }
}

resources/views/employees/create.blade.php
@extends("theme.$theme.layout")

@section('content')
    <div class="row">
        <div class="col-lg-12">
            @include('includes.form-error')
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3>@lang('view.employees.form.title_form')</h3>
                </div>
                <div class="box-body">
                    <form role="form" action="{{route('employees.store')}}" method="post" enctype="multipart/form-data" autocomplete="off">
                        @csrf
                        <div class="box-body">
                            @include('employees.form')
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            @include('includes.btn-form-create')
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/employees/edit.blade.php
@extends("theme.$theme.layout")

@section('content')
    <div class="row">
        <div class="col-lg-12">
            @include('includes.form-error')
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3>@lang('view.companies.form.title_form')</h3>
                </div>
                <div class="box-body">
                    <form role="form" action="{{route('employees.update', $employee)}}" method="post" enctype="multipart/form-data" autocomplete="off">
                        @csrf
                        @method('PUT')
                        <div class="box-body">
                            @include('employees.form')
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            @include('includes.btn-form-edit')
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/employees/form.blade.php
<div class="form-group">
    <label for="exampleInputName" class="required">@lang('view.employees.form.name')</label>
    <input type="text" class="form-control" id="exampleInputName" name="name" placeholder="Enter name"
           value="{{old('name', $employee->name ?? '')}}" required>
</div>
<div class="form-group">
    <label for="exampleInputLastName" class="required">@lang('view.employees.form.last_name')</label>
    <input type="text" class="form-control" id="exampleInputLastName" name="last_name" placeholder="Enter last name"
           value="{{old('last_name', $employee->last_name ?? '')}}" required>
</div>
<div class="form-group">
    <label for="exampleInputEmail1">@lang('view.employees.form.email')</label>
    <input type="email" class="form-control" id="exampleInputEmail1" name="email" placeholder="Enter email"
           value="{{old('email', $employee->email ?? '')}}">
</div>
<div class="form-group">
    <label for="exampleInputCompany">@lang('view.employees.form.name_company')</label>
    <select class="form-control" name="company_id" id="exampleInputCompany">
        @if(isset($companies) && count($companies) > 0)
            @foreach($companies as $company)
                @if(isset($employee))
                    <option {{$selected = ($company->id == $employee->company->id) ? 'selected="selected"' : ''}} value='{{ $company->id }}'>{{ $company->name }}</option>
                @else
                    <option value='{{ $company->id }}'>{{ $company->name }}</option>
                @endif
            @endforeach
        @endif
    </select>
</div>
<div class="form-group">
    <label for="exampleInputPhone">@lang('view.employees.form.phone')</label>
    <input type="number" class="form-control" id="exampleInputPhone" name="phone" placeholder="Enter phone"
           value="{{old('phone', $employee->phone ?? '')}}">
</div>

resources/views/employees/index.blade.php
@extends("theme.$theme.layout")

@section('content')
    <div class="row">
        <div class="col-lg-12">
            @include('includes.message')
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3>List Employees</h3> <a href="{{url('employees/create')}}" class="btn btn-success">Create new
                        employee</a>
                </div>
                <div class="box-body">
                    @if(isset($employees) && count($employees) > 0)
                        <table class="table table-bordered">
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>Name</th>
                                <th>Last name</th>
                                <th>Email</th>
                                <th>Company</th>
                                <th>phone</th>
                                <th>Actions</th>
                            </tr>
                            @foreach($employees as $key => $employee)
                                <tr>
                                    <td>{{$key + 1}}</td>
                                    <td>{{$employee->name}}</td>
                                    <td>{{$employee->last_name}}</td>
                                    <td>{{$employee->email}}</td>
                                    <td>{{$employee->company->name}}</td>
                                    <td>{{$employee->phone}}</td>
                                    <td>
                                        <form action="{{ route('employees.destroy',$employee->id) }}" method="POST">
                                            <a href="{{url('employees/' . $employee->id , 'edit')}}"
                                               class="btn btn-primary">Edit</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                        {{ $employees->links() }}
                    @else
                        Empty data
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection